CREATE TABLE historico_financeiro
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    emprestimo_id BIGINT                                  NOT NULL,
    tipo          VARCHAR(255),
    valor         DECIMAL,
    data_evento   date,
    observacao    VARCHAR(255),
    CONSTRAINT pk_historico_financeiro PRIMARY KEY (id)
);

ALTER TABLE emprestimo
    ADD dias_em_atraso INTEGER;

ALTER TABLE emprestimo
    ADD juros_atraso DECIMAL;

ALTER TABLE emprestimo
    ADD multa DECIMAL;

ALTER TABLE historico_financeiro
    ADD CONSTRAINT FK_HISTORICO_FINANCEIRO_ON_EMPRESTIMO FOREIGN KEY (emprestimo_id) REFERENCES emprestimo (id);