CREATE TABLE cliente
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    cpf      VARCHAR(255),
    rg       VARCHAR(255),
    endereco VARCHAR(255),
    telefone VARCHAR(255),
    CONSTRAINT pk_cliente PRIMARY KEY (id)
);

CREATE TABLE emprestimo
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor_emprestimo       DECIMAL,
    taxa_juros_mensal      DECIMAL,
    prazo                  INTEGER,
    data_inicio_contrato   date,
    valor_parcela          DECIMAL,
    totalapagar            DECIMAL,
    cliente_id             BIGINT,
    total_pago             DECIMAL,
    num_parcelas_pagas     INTEGER,
    valor_em_aberto        DECIMAL,
    proximo_vencimento     date,
    status_emprestimo_enum VARCHAR(255),
    valor_divida_anterior  DECIMAL,
    valor_garantia         DECIMAL,
    detalhes_garantia      VARCHAR(255),
    CONSTRAINT pk_emprestimo PRIMARY KEY (id)
);

ALTER TABLE emprestimo
    ADD CONSTRAINT FK_EMPRESTIMO_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);